//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DovizKurlarınıCekme.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsoleDbProjeEntities2 : DbContext
    {
        public ConsoleDbProjeEntities2()
            : base("name=ConsoleDbProjeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Currency> Tbl_Currency { get; set; }
        public virtual DbSet<Tbl_CurrencyValue> Tbl_CurrencyValue { get; set; }
        public virtual DbSet<Tbl_Operation> Tbl_Operation { get; set; }
    }
}
