//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DovizKurlarınıCekme.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Currency()
        {
            this.Tbl_CurrencyValue = new HashSet<Tbl_CurrencyValue>();
            this.Tbl_Operation = new HashSet<Tbl_Operation>();
        }
    
        public int ID { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencySymbol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CurrencyValue> Tbl_CurrencyValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Operation> Tbl_Operation { get; set; }
    }
}
